services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - WORDPRESS_DB_HOST=$MYSQL_HOST
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_PORT=$MYSQL_PORT
      - WORDPRESS_AUTH_KEY=$WP_AUTH_KEY
      - WORDPRESS_SECURE_AUTH_KEY=$WP_SECURE_AUTH_KEY
      - WORDPRESS_LOGGED_IN_KEY=$WP_LOGGED_IN_KEY
      - WORDPRESS_NONCE_KEY=$WP_NONCE_KEY
      - WORDPRESS_AUTH_SALT=$WP_AUTH_SALT
      - WORDPRESS_SECURE_AUTH_SALT=$WP_SECURE_AUTH_SALT
      - WORDPRESS_LOGGED_IN_SALT=$WP_LOGGED_IN_SALT
      - WORDPRESS_NONCE_SALT=$WP_NONCE_SALT
      - WORDPRESS_CONFIG_EXTRA=define('WP_CACHE', true);define('DISABLE_WP_CRON', true);define('WP_POST_REVISIONS', 10);define('WP_MEMORY_LIMIT', '512M');define('FS_METHOD','direct');define('DISALLOW_FILE_MODS',false);define('DISALLOW_FILE_EDIT',true);define('WP_AUTO_UPDATE_CORE',true);define('WP_REDIS_HOST','$REDIS_HOST');define('WP_REDIS_PORT','$REDIS_PORT');define('WP_REDIS_USERNAME','$REDIS_USERNAME');define('WP_REDIS_DATABASE','$REDIS_DATABASE');define('WP_REDIS_PASSWORD','$REDIS_PASSWORD');define('SMTP_HOST','$SMTP_HOST');define('SMTP_PORT','$SMTP_PORT');define('SMTP_AUTH','$SMTP_AUTH');define('SMTP_USER','$SMTP_USER');define('SMTP_PASS','$SMTP_PASS');define('SMTP_FROM','$SMTP_FROM');define('SMTP_FROMNAME','$SMTP_FROMNAME');
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1" ]
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  wordpress-files:
    driver: local
